In [47]:
import numpy as np

In [48]:
# Single-dimensional Array

np1 = np.array([10,20,30])
print("Single-dimensional Array\n",np1)
print(type(np1))
print()

# Multi-dimensional Array

np2 = np.array([[10,20,30],[40,50,60]])
print("Multi-dimensional Array\n",np2)
print(type(np2))


Single-dimensional Array
 [10 20 30]
<class 'numpy.ndarray'>

Multi-dimensional Array
 [[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>


In [49]:
# Creating Numpy Array with zeros
np1 = np.zeros((1,2)) # (1,2) shape
print(np1)
print()
np1 = np.zeros((5,5)) # (5,5) shape
print(np1)

[[0. 0.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [50]:
# Create Numpy Array with same number

np1 = np.full((2,2),10) # (2,2) is shape , 10 is value
print(np1)

np1 = np.full((2,3),[10,5,2]) # (2,3) is shape
                               # [10,5,2] is value depend the colunmn
print(np1)


[[10 10]
 [10 10]]
[[10  5  2]
 [10  5  2]]


In [51]:
# Create Numpy Array within a range

n1 = np.arange(10,20) # 10 start
                      # 20 the end but it not included, the last will be 19
print(n1)

n1 = np.arange(1,300,27)  # 1 start, 300 end, 27 is interval each value
print(n1)

[10 11 12 13 14 15 16 17 18 19]
[  1  28  55  82 109 136 163 190 217 244 271 298]


In [52]:
# Create Numpy Array with random numbers

np1 = np.random.randint(1,100,9)  # the random number is in range 1 - 100, take 9 number
print(np1)

[58 33  1 45 90 65 92 10 68]


In [53]:
# Check the shape

np1 = np.array([[1,2,3],[5,6,4]])
print(np1, "\n", "shape : ",np1.shape)

# change the shape
np1.shape = (3,2)
print(np1, "\n","shape : ", np1.shape)

[[1 2 3]
 [5 6 4]] 
 shape :  (2, 3)
[[1 2]
 [3 5]
 [6 4]] 
 shape :  (3, 2)


In [57]:
# Joining Numpy Array

np1 = np.array([1,2,3])
np2 = np.array([9,8,7])

# vstack() => vertical stack
np3 = np.vstack((np1,np2))
print("vstack() \n =>",np3)

# hstack() => horizontal stack
np3 = np.hstack((np1,np2))
print("hstack() \n =>",np3)

# column_stack
np3 = np.column_stack((np1,np2))
print("column_stack() \n =>",np3)


vstack() 
 => [[1 2 3]
 [9 8 7]]
hstack() 
 => [1 2 3 9 8 7]
column_stack() 
 => [[1 9]
 [2 8]
 [3 7]]


In [63]:
# Nmpy Intersection & Difference

# its return new array
# Intersection is the same number of 2 arrays
# Difference is as like the name the difference of 2 arrays

n1 = np.array([10,20,30,40,50,60])
n2 = np.array([40,60,70,80,90])

# Intersection

np3 = np.intersect1d(n1,n2)   # interseciton from n1 to n2
print("Intersection n1 to n2 =>",np3)

np3 = np.intersect1d(n2,n1)   # interseciton from n1 to n2
print("Intersection n1 to n2 =>",np3)   # same result as before


# Difference
np3 = np.setdiff1d(n1,n2)   # difference n1 to n2
print("Difference n1 to n2 =>",np3)

np3 = np.setdiff1d(n2,n1)   # difference n2 to n1
print("Difference n2 to n1 =>",np3)



Intersection n1 to n2 => [40 60]
Intersection n1 to n2 => [40 60]
Difference n1 to n2 => [10 20 30 50]
Difference n2 to n1 => [70 80 90]


In [83]:
# Addition of NUmpy Arrays

np1 = np.array([10,20])
np2 = np.array([80,90])
np3 = np.array([80,90])
print(np1)
print(np2)
print(np3)

np4 = np.sum([np1,np2,np3])  # this to sum the all array
print("sum all =>", np4)

np4 = np.sum([np1,np2],axis=0)  # column
print("sum with axis 0 =>", np4) 

np4 = np.sum([np1,np2],axis=1)  # row
print("sum with axis 1 =>", np4)


print("\n=== With multi-dimension array ===")
# try with multidimension array

np1 = np.array([[10,20],[3,5]])
np2 = np.array([[80,90],[8,9]])
np3 = np.array([[80,90],[9,8]])
print(np1)
print(np2)
print(np3)

np4 = np.sum([np1,np2,np3])  # this to sum the all array
print("sum all =>", np4)

np4 = np.sum([np1,np2],axis=0)  # column
print("sum with axis 0 =>", np4) 

np4 = np.sum([np1,np2],axis=1)  # row
print("sum with axis 1 =>", np4)

[10 20]
[80 90]
[80 90]
sum all => 370
sum with axis 0 => [ 90 110]
sum with axis 1 => [ 30 170]

=== With multi-dimension array ===
[[10 20]
 [ 3  5]]
[[80 90]
 [ 8  9]]
[[80 90]
 [ 9  8]]
sum all => 412
sum with axis 0 => [[ 90 110]
 [ 11  14]]
sum with axis 1 => [[13 25]
 [88 99]]


In [92]:
# Numpy Array Mathematic


np1 = np.array([10,20,40])

# Basic Addition
np2 = np1+2
print("+2 =>", np2)

np3= np1-2
print("-2 =>",np3)

np4= np1*2
print("*2 =>",np4)

np5= np1%2
print("%2 =>",np5)

np6 = np1/2
print("/2 =>",np6)

np7= np1**2
print("**2 =>",np7)




+2 => [12 22 42]
-2 => [ 8 18 38]
*2 => [20 40 80]
%2 => [0 0 0]
/2 => [ 5. 10. 20.]
**2 => [ 100  400 1600]


In [93]:
# Numpy Math Function

np1 = np.array([10,20,30,50,60])

# Mean 
npr = np.mean(np1)
print("mean => ",npr)

# Median 
npr = np.median(np1)
print("median => ",npr)

# Standard Deviation 
npr = np.std(np1)
print("std => ",npr)


mean =>  34.0
median =>  30.0
std =>  18.547236990991408


In [94]:
# Saving and Loading Numpy Array

np1 = np.array([10,20,30,40,50,60])

np.save("final_numpy_array", np1)

if you execute the code before check the directory the numpy file will show

In [95]:
np2 = np.load("final_numpy_array.npy")
print(np2)

[10 20 30 40 50 60]
